# 定义云构建
main:
  push:
    - name: 同步仓库
      stages:
        - name: 同步 Github 仓库
          imports: 
            - https://cnb.cool/SinzMise/szn-cnb-keys/-/blob/main/github-cnb-push.yml
          script: |
            git remote add github https://x-access-token:$GITHUB_TOKEN@github.com/SinzMise/homepage-re
            git push github main
  